name: Autolog
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  generate-changelog:
    name: Generate Changelog

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            breaking: Breaking Changes
            feat: New Features
            fix: Bug Fixes
            revert: Reverts
            perf: Performance Improvements
            refactor: Refactors
            deps: Dependencies
            docs: Documentation Changes
            style: Code Style Changes
            build: Build System
            ci: Continuous Integration
            test: Tests
            chore: Chores
            other: Other Changes
          default-commit-type: Default Type
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false
