name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  autolog:
    uses: ./.github/workflows/autolog.yml

  release:
    name: Create Release

    concurrency: github-release

    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    runs-on: ubuntu-latest

    needs:
      - autolog

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Changelog
        uses: ardalanamini/auto-changelog@master
        id: changelog

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_TOKEN }}
